#### Import NumPy 

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
np.full((10),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
np.arange(10,51,1)
  

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#np.linspace(10,51,50)

array([10.        , 10.83673469, 11.67346939, 12.51020408, 13.34693878,
       14.18367347, 15.02040816, 15.85714286, 16.69387755, 17.53061224,
       18.36734694, 19.20408163, 20.04081633, 20.87755102, 21.71428571,
       22.55102041, 23.3877551 , 24.2244898 , 25.06122449, 25.89795918,
       26.73469388, 27.57142857, 28.40816327, 29.24489796, 30.08163265,
       30.91836735, 31.75510204, 32.59183673, 33.42857143, 34.26530612,
       35.10204082, 35.93877551, 36.7755102 , 37.6122449 , 38.44897959,
       39.28571429, 40.12244898, 40.95918367, 41.79591837, 42.63265306,
       43.46938776, 44.30612245, 45.14285714, 45.97959184, 46.81632653,
       47.65306122, 48.48979592, 49.32653061, 50.16326531, 51.        ])

#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
np.random.uniform(0,1,size=(1,1))

array([[0.33255226]])

In [ ]:
np.random.rand()

0.08650967815679633

In [ ]:
'''
np.random.randint(1,100,size=(5,5))
'''

'\nnp.random.randint(1,100,size=(5,5))\n'

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.normal(size=(1,25))

array([[-1.78038599, -1.1799895 , -0.66724648, -1.63057123,  1.01645926,
         0.0623205 ,  0.50852642,  0.10391821,  0.24861127,  1.33132755,
         0.83677571,  0.74349767, -0.87591461, -1.66782434, -0.17955775,
         0.14380857,  0.34933705,  0.29234363, -0.80476825, -0.53045604,
         0.442105  ,  0.33620412, -0.67027691, -0.38952845, -1.06195768]])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix: -!del!-

In [ ]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

#### Create an array of 20 linearly spaced points between 0 and 1: 

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([12,13,14,15,16,18,19,20,22,23,24,25]).reshape(3,4)

array([[12, 13, 14, 15],
       [16, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([20],ndmin=0)

array([20])

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.array([2,7,12]).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([21,22,23,24,25])

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
x=np.array([55,60,65,70,75])
np.sum(x)

325

#### Get the standard deviation of the values in mat

In [ ]:
x=np.array([55,60,65,70,75])
np.std(x)

7.0710678118654755

#### Get the sum of all the columns in mat

In [ ]:
x=np.array([55,60,65,70,75])
np.sum(x,axis=0)

325

array([55, 60, 65, 70, 75])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
x=np.array([[1,2],[2,3]])
y=np.array([[4,5],[6,7]])
np.dot(x,y)

array([[16, 19],
       [26, 31]])

####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
'''
x=np.array([[1.3,2.5,3.6,np.nan],[2.6,3.3,np.nan,5.5],[2.1,3.2,5.4,6.5]])
l=x.mean(axis=1).tolist()
print(l)
for i in x:
  for j in i:
    if j==np.nan:
      j=l[i]
print(x)
'''

[nan, nan, 4.300000000000001]
[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]


In [ ]:
# Initialising numpy array
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
  
# printing initial array
print ("initial array", ini_array)
  
# column mean
col_mean = np.nanmean(ini_array, axis =0)
  
# printing column mean
print ("columns mean",list(col_mean))
  
# find indices where nan value is present
inds = np.where(np.isnan(ini_array))

# replace inds with avg of column
ini_array[inds] = np.take(col_mean, inds[1])
  
# printing final array
print ("final array", ini_array)

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
columns mean [2.0, 3.0, 4.5, 6.0]
final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [ ]:
'''
Searching
x=np.array([1,3,4])
if 7 in x:
  print("Element is found")
else:
  print("Nothing is found")
'''

Nothing is found


# You're done!

In [ ]:
import pandas as pd
df = pd.read_csv("/content/data (1).csv")

#Pandas

##### First 5 rows:

In [ ]:
df.head()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0        0.0102         0.833       204600   0.434   
1           1        0.1990         0.743       326933   0.359   
2           2        0.0344         0.838       185707   0.412   
3           3        0.6040         0.494       199413   0.338   
4           4        0.1800         0.678       392893   0.561   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1          0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2          0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3          0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4          0.512000    5    0.4390   -11.648     0       0.0694  174.004   

   time_signature  valence  target      song_title            artist  
0             4.0    0.286       1        Mask Off            Future  
1             4.0    0.588       1         Redbone  Childish Gambino  
2             4.0    0.173       1    Xanny Family            Future  
3             4.0    0.230       1  Master Of None       Beach House  
4             4.0    0.904       1  Parallel Lines       Junior Boys

##### Last 5 rows:

In [ ]:
df.tail()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
2012        2012       0.00106         0.584       274404   0.932   
2013        2013       0.08770         0.894       182182   0.892   
2014        2014       0.00857         0.637       207200   0.935   
2015        2015       0.00164         0.557       185600   0.992   
2016        2016       0.00281         0.446       204520   0.915   

      instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
2012          0.002690    1    0.1290    -3.501     1        0.333   74.976   
2013          0.001670    1    0.0528    -2.663     1        0.131  110.041   
2014          0.003990    0    0.2140    -2.467     1        0.107  150.082   
2015          0.677000    1    0.0913    -2.735     1        0.133  150.011   
2016          0.000039    9    0.2180    -6.221     1        0.141  190.013   

      time_signature  valence  target                            song_title  \
2012             4.0    0.211       0   Like A Bitch - Kill The Noise Remix   
2013             4.0    0.867       0                                 Candy   
2014             4.0    0.470       0  Habit - Dack Janiels & Wenzday Remix   
2015             4.0    0.623       0                         First Contact   
2016             4.0    0.402       0                    I Wanna Get Better   

              artist  
2012  Kill The Noise  
2013  Dillon Francis  
2014        Rain Man  
2015      Twin Moons  
2016       Bleachers

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        2017 non-null   int64  
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64  
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64  
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64  
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64  
 15  song_title        2017 non-null   object 
 16  artist            2017 non-null   object 


#####Inference: There are 16 columns in the DataFrame. We can also observe that there are 2017 data points.There are no Null values.Datatypes of all the columns are mentioned in the data frame.

In [ ]:
#df.sort_values('danceability')[['song_title', 'artist']].head(10)

In [ ]:
#df.sort_values('duration_ms',ascending=False)[['song_title', 'artist', 'duration_ms']].head(10)

In [ ]:
#df_filt = df[df['duration_ms'] < 400000]

In [ ]:
'''
df2= df_filt.sort_values('energy',ascending=False)[['song_title', 'energy']].head(10)
print(df2)
'''

"\ndf2= df_filt.sort_values('energy',ascending=False)[['song_title', 'energy']].head(10)\nprint(df2)\n"

Q)Find songs with value for energy column greater than 0.4 and display values for song_title column.

In [ ]:
newdf=df[df['energy']>0.4]
newdf[['song_title']]

song_title
0                                 Mask Off
2                             Xanny Family
4                           Parallel Lines
5                                 Sneakin’
6                              Childs Play
...                                    ...
2012   Like A Bitch - Kill The Noise Remix
2013                                 Candy
2014  Habit - Dack Janiels & Wenzday Remix
2015                         First Contact
2016                    I Wanna Get Better

[1830 rows x 1 columns]

Q)For songs with duration duration_ms value less than 300000 ms (300 s), find Top 10 “fastest” songs( songs with highest values for tempo column ) and display values for song_title, artistcolumns.

In [ ]:
newdf=df[df['duration_ms']<300000]
newdf.sort_values('tempo',ascending=False)[['song_title','artist']].head(10)

song_title            artist
124       Danger and Dread        Brown Bird
718            Hannah Hunt   Vampire Weekend
1960            Puppy Love      Donny Osmond
1711               Amazing     Big Time Rush
809        Tupelo - Part 1       Pop Staples
826     Living Every Dream            Antwon
1339  The Shaping Sickness  Shadow of Intent
102         Willing & Able        Disclosure
1802             Mad Love.              JoJo
532        Wake Bake Skate            FIDLAR

####ascending=False is used for arranging the dataframe in a descending order according to the tempo & head() gives the top 10 entries.

#####Q) Find songs with value for artist column = Drake and value for energy column greater than 0.5 and display values for song_title & artist column.

In [ ]:
newdf=df[df['energy']>0.5][['song_title','artist']]

In [ ]:
newdf[newdf['artist']=='Drake'][['song_title','artist']]

song_title artist
5                    Sneakin’  Drake
37                    Jumpman  Drake
117             Hotline Bling  Drake
154                 Big Rings  Drake
440                 Headlines  Drake
589   Started From the Bottom  Drake
779   0 To 100 / The Catch Up  Drake
1016         Skepta Interlude  Drake
1218          Best I Ever Had  Drake
1223                Take Care  Drake

#####Q)Create a dataframe of the songs that rank among top 10 for the instrumentalness metric. This dataframe should only contain the instrumentalness, song title and artist columns.


In [ ]:
df.sort_values('instrumentalness',ascending=False)[['instrumentalness','artist','song_title']].head(10)

instrumentalness                    artist  \
1313             0.976        Signs of the Swarm   
271              0.968               Prince Rama   
1575             0.964                Ray Bryant   
1619             0.958             John Dahlbäck   
725              0.957                Todd Terje   
1546             0.956         Jan Lundgren Trio   
1322             0.955  Walking Dead On Broadway   
1349             0.954           Aversions Crown   
1661             0.954               Mark Knight   
121              0.952                Bassnectar   

                                song_title  
1313                       Senseless Order  
271   So Destroyed (channeling Rage Peace)  
1575             A Hundred Dreams from Now  
1619                                 Raven  
725                      Strandbar (disko)  
1546                        Almas vaggvisa  
1322                            Pitchblack  
1349                       Prismatic Abyss  
1661                               Yebisah  
121                         Chasing Heaven

####ascending=False is used for arranging the dataframe in a descending order according to instrunmentalness.

#####Q)Create a dataframe of the average tempo for each of the top 10 most occurring artists.

In [ ]:
x=df['artist'].value_counts(dropna=False)
pd.DataFrame(x).sort_values('artist',ascending=False).head(10)

artist
Drake                16
Rick Ross            13
Disclosure           12
WALK THE MOON        10
Backstreet Boys      10
Crystal Castles       9
FIDLAR                9
Future                8
Skrillex              8
Big Time Rush         8

df['artist'].value_counts(dropna=False) gives the count of each artist.
dropna=False is used as it also counts the missing values if present in a dataset.

In [ ]:
df.groupby('artist').count().sort_values('artist',ascending=False).head(10)['tempo']

artist
플랫핏 Flat Feet         1
카우칩스 The CowChips     1
도시총각 Dosichonggak     1
권나무 Kwon Tree         1
tobyMac               1
tUnE-yArDs            2
one sonic society     1
for KING & COUNTRY    2
deadmau5              2
alt-J                 1
Name: tempo, dtype: int64